language: ruby
branches:
  only:
    - master
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
matrix:
  exclude:
    - rvm: 2.4.7
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.3.8
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.2.10
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.4.7
      env: "RAILS_VERSION=4.2.0"
    - rvm: 2.5.6
      env: "RAILS_VERSION=4.2.0"
    - rvm: 2.6.4
      env: "RAILS_VERSION=4.2.0"
sudo: false
